// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qzigt_629xzpg7cNLj_A4nvo-GJ1G0U',
    appId: '1:273294066360:web:20f99236ff8285a09f2a4d',
    messagingSenderId: '273294066360',
    projectId: 'smart-vision-41221',
    authDomain: 'smart-vision-41221.firebaseapp.com',
    storageBucket: 'smart-vision-41221.firebasestorage.app',
    measurementId: 'G-GHPN12W63Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqY8f9x7Bpl-5GfGu0gFBg4NJfhGMmXuM',
    appId: '1:273294066360:android:7308f2050caae7f49f2a4d',
    messagingSenderId: '273294066360',
    projectId: 'smart-vision-41221',
    storageBucket: 'smart-vision-41221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvOyHexSwz1T9lzJ1IM53G4peF2M1ENc',
    appId: '1:273294066360:ios:75e9da12dfd21a569f2a4d',
    messagingSenderId: '273294066360',
    projectId: 'smart-vision-41221',
    storageBucket: 'smart-vision-41221.firebasestorage.app',
    iosBundleId: 'com.example.smartVision',
  );
}
